# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 12:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insta_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=256, verbose_name='Id')),
                ('tag_title', models.CharField(max_length=256, verbose_name='Title')),
                ('tag_images_count', models.IntegerField(blank=True, verbose_name='Image count')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='InstaBotTask',
            fields=[
                ('task_id', models.CharField(blank=True, max_length=256, primary_key=True, serialize=False, verbose_name='Task id')),
                ('operation', models.CharField(max_length=256, null=True, verbose_name='Operation')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='User_login')),
                ('status', models.CharField(blank=True, max_length=256, null=True, verbose_name='Status')),
                ('create_time', models.CharField(blank=True, max_length=256, null=True, verbose_name='Create time')),
                ('count', models.CharField(blank=True, max_length=256, null=True, verbose_name='Count')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='InstaMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=256, verbose_name='Id')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('likes_count', models.CharField(blank=True, max_length=256, verbose_name='Likes count')),
                ('code', models.CharField(blank=True, max_length=256, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
            },
        ),
        migrations.CreateModel(
            name='InstaMediaSRC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_src', models.CharField(max_length=256, verbose_name='SRC')),
                ('insta_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srcs', to='shopapp.InstaMedia')),
            ],
            options={
                'verbose_name': 'Media src',
                'verbose_name_plural': 'Media srcs',
            },
        ),
        migrations.CreateModel(
            name='InstaShopItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Name')),
                ('price', models.CharField(max_length=256, verbose_name='Price')),
                ('category', models.CharField(blank=True, max_length=256, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.InstaMedia')),
            ],
            options={
                'verbose_name': 'Shop item',
                'verbose_name_plural': 'Shop items',
            },
        ),
        migrations.CreateModel(
            name='InstaUser',
            fields=[
                ('user_id', models.CharField(blank=True, max_length=256, primary_key=True, serialize=False, verbose_name='Id')),
                ('user_name', models.CharField(max_length=256, null=True, verbose_name='User_login')),
                ('user_full_name', models.CharField(max_length=256, null=True, verbose_name='User_full_name')),
                ('followers_count', models.IntegerField(blank=True, null=True)),
                ('follow_count', models.IntegerField(blank=True, null=True)),
                ('profile_pic_url_hd', models.CharField(blank=True, max_length=256, null=True)),
                ('user_biography', models.CharField(blank=True, max_length=256, null=True)),
                ('user_external_url', models.CharField(blank=True, max_length=256, null=True)),
                ('follows_viewer', models.CharField(blank=True, max_length=256, null=True)),
                ('followed_by_viewer', models.CharField(blank=True, max_length=256, null=True)),
                ('has_requested_viewer', models.CharField(blank=True, max_length=256, null=True)),
                ('requested_by_viewer', models.CharField(blank=True, max_length=256, null=True)),
                ('has_blocked_viewer', models.CharField(blank=True, max_length=256, null=True)),
                ('blocked_by_viewer', models.CharField(blank=True, max_length=256, null=True)),
                ('is_private', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'InstaUser',
                'verbose_name_plural': 'InstaUser',
            },
        ),
        migrations.CreateModel(
            name='InstaUserCred',
            fields=[
                ('user_login', models.CharField(blank=True, max_length=256, primary_key=True, serialize=False, verbose_name='Login')),
                ('user_pass', models.CharField(max_length=256, null=True, verbose_name='Password')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InstaUserCred',
                'verbose_name_plural': 'InstaUsersCreds',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('mail', models.CharField(max_length=256, verbose_name='Mail')),
                ('phone', models.CharField(max_length=256, verbose_name='Phone')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('comment', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=256, verbose_name='Count')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopapp.Order')),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopapp.InstaShopItem')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('rel_id', models.AutoField(primary_key=True, serialize=False)),
                ('followed_user_id', models.CharField(max_length=256, null=True, verbose_name='Followed user id')),
                ('user_id', models.CharField(max_length=256, null=True, verbose_name='User id')),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
            },
        ),
        migrations.CreateModel(
            name='Task_to_user_map',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.InstaBotTask')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.InstaUser')),
            ],
            options={
                'verbose_name': 'Task_to_user_map',
                'verbose_name_plural': 'Task_to_user_maps',
            },
        ),
        migrations.CreateModel(
            name='TaskTarget',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='User_name')),
                ('tag_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tag_name')),
                ('photo_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo_id')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='shopapp.InstaBotTask')),
            ],
            options={
                'verbose_name': 'Task_to_arg_map',
                'verbose_name_plural': 'Task_to_arg_maps',
            },
        ),
        migrations.AddField(
            model_name='instamedia',
            name='image_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.InstaUser'),
        ),
    ]
